export interface ProcessResponseReport {
  id: number;
  type: number;
  processType: string;
  customerId: number;
  customerName: string;
  walletId: number;
  senderWalletNo: string;
  currencyId: number;
  currency: string;
  value: number;
  fee: number;
  total: number;
  defRate: number;
  exRate?: number | null;
  receiverId?: number | null;
  receiverName: string;
  receiverWalletId?: number | null;
  receiverWalletNo: string;
  receiverCurrencyId?: number | null;
  receiverCurrency: string;
  receiverValue?: number | null;
  receiverDefRate?: number | null;
  status: number;
  statusClass: string;
  statusDisplay: string;
  statusDate: Date;
  description: string;
  riskScore: number;
  ip: string;
  cDate: Date;
  uDate: Date;
  referenceNumber: string;
}
